version: '3'

services:
  app:
    build: kevinduy/python
    tty: true
    restart: always
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "8000:8000"
      - "4200:4200"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: homestead
